version: '3'

services:
  db:
    image: mariadb:latest
    container_name: MakeIT-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: member
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - database:/var/lib/mysql
    ports:
        - 3306:3306
  
volumes:
  database:
